/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.Date;
import java.sql.Connection;

/**
 *
 * @author santhoshkumar
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }
    
    //to get book details from DB
    public void getbookDetails(){
        int bid = Integer.parseInt(txtbookid.getText());
        
        try{
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pst = conn.prepareStatement("select * from book_details where bookid = ?");
            pst.setInt(1, bid);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                ibookid.setText(rs.getString("bookid"));
                ibookname.setText(rs.getString("bookname"));
                ibookauthor.setText(rs.getString("author"));
                ibookquantity.setText(rs.getString("quantity"));
            }else{
                bookerror.setText("invalid book details");
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        
    }
    
    public void getuserDetails(){
        int sid = Integer.parseInt(txtuserid.getText());
        
        try{
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pst = conn.prepareStatement("select * from user_details where studentid = ?");
            pst.setInt(1, sid);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                iuserid.setText(rs.getString("studentid"));
                iusername.setText(rs.getString("name"));
                icourse.setText(rs.getString("course"));
                ibranch.setText(rs.getString("branch"));
            }else{
                studenterror.setText("Invalid Student details");
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        
    }
    
    public boolean issueBook(){
        boolean isissued = false;
        int bid = Integer.parseInt(txtbookid.getText());
        int sid = Integer.parseInt(txtuserid.getText());
        String bname = ibookname.getText();
        String sname = iusername.getText();
        Date uIssuedate = issuedate.getDatoFecha();
        Date uDuedate = duedate.getDatoFecha();
        
        Long l1 = uIssuedate.getTime();
        Long l2 = uDuedate.getTime();
        
        java.sql.Date sIssueDate = new java.sql.Date(l1);
        java.sql.Date sDueDate = new java.sql.Date(l2);
        
        try{
            Connection conn = DatabaseConnection.getConnection();
            String sql = "Insert into issue_details(bookid,bookname,userid,username,issue_date,due_date,status) values(?,?,?,?,?,?,?)";
            PreparedStatement pst =conn.prepareStatement(sql);
            pst.setInt(1, bid);
            pst.setString(2, bname);
            pst.setInt(3,sid);
            pst.setString(4,sname);
            pst.setDate(5, sIssueDate);
            pst.setDate(6,sDueDate);
            pst.setString(7, "pending");
            
            int rowcount = pst.executeUpdate();
            if(rowcount > 0){
                isissued = true;
            }else{
                isissued = false;
            }
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
        return isissued;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ibranch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iuserid = new javax.swing.JLabel();
        iusername = new javax.swing.JLabel();
        icourse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studenterror = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ibookquantity = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ibookid = new javax.swing.JLabel();
        ibookname = new javax.swing.JLabel();
        ibookauthor = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bookerror = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbookid = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        txtuserid = new app.bolivia.swing.JCTextField();
        issuedate = new rojeru_san.componentes.RSDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        duedate = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Branch:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 190, 30));

        ibranch.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        ibranch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ibranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 190, 30));

        jLabel5.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        jLabel6.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 30));

        jLabel7.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("user ID:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 30));

        iuserid.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        iuserid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 30));

        iusername.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        iusername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(iusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 190, 30));

        icourse.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        icourse.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(icourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 30));

        jLabel4.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
        jLabel4.setText("User Details");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 100));

        studenterror.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        studenterror.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(studenterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 290, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 810));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 153, 255));
        jLabel11.setFont(new java.awt.Font("Kailasa", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel12.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("Book Details");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 100));

        ibookquantity.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        ibookquantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ibookquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 190, 30));

        jLabel15.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Book Name:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        jLabel16.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Author:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 30));

        jLabel17.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Book ID:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 30));

        ibookid.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        ibookid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ibookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 30));

        ibookname.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        ibookname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ibookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 190, 30));

        ibookauthor.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        ibookauthor.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ibookauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 30));

        jLabel19.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Quantity:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 190, 30));

        bookerror.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        bookerror.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(bookerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 290, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 810));

        jLabel1.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        jLabel1.setText("Issue Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 230, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Kailasa", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 20, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 140, 50));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Book ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 240, 40));

        txtbookid.setBackground(new java.awt.Color(204, 204, 204));
        txtbookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtbookid.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txtbookid.setPhColor(new java.awt.Color(255, 255, 255));
        txtbookid.setPlaceholder("Enter book ID");
        txtbookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookidFocusLost(evt);
            }
        });
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Issue Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 240, 40));

        txtuserid.setBackground(new java.awt.Color(204, 204, 204));
        txtuserid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtuserid.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txtuserid.setPhColor(new java.awt.Color(255, 255, 255));
        txtuserid.setPlaceholder("Enter User ID");
        txtuserid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuseridFocusLost(evt);
            }
        });
        jPanel1.add(txtuserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, -1, -1));

        issuedate.setColorBackground(new java.awt.Color(0, 0, 0));
        issuedate.setColorForeground(new java.awt.Color(0, 0, 0));
        issuedate.setPlaceholder("Select Issue Date");
        jPanel1.add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 400, 190, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setText("User ID");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 240, 40));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setText("Due Date");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 240, 40));

        duedate.setColorBackground(new java.awt.Color(0, 0, 0));
        duedate.setColorForeground(new java.awt.Color(0, 0, 0));
        duedate.setPlaceholder("Select Due Date");
        jPanel1.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, 190, -1));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonCircle1.setText("Issue Book");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 600));

        setSize(new java.awt.Dimension(1301, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtbookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookidFocusLost
        // TODO add your handling code here:
        
        if(!txtbookid.getText().equals("")){
            getbookDetails();
            
        }
        
    }//GEN-LAST:event_txtbookidFocusLost

    private void txtuseridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuseridFocusLost
        // TODO add your handling code here:
        
        if(!txtuserid.getText().equals("")){
            getuserDetails();
            
        }
    }//GEN-LAST:event_txtuseridFocusLost

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        if(issueBook()== true){
            JOptionPane.showMessageDialog(this,"book issued successfully");
        }else{
            JOptionPane.showMessageDialog(this,"book cannot issued");
        }
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookerror;
    private rojeru_san.componentes.RSDateChooser duedate;
    private javax.swing.JLabel ibookauthor;
    private javax.swing.JLabel ibookid;
    private javax.swing.JLabel ibookname;
    private javax.swing.JLabel ibookquantity;
    private javax.swing.JLabel ibranch;
    private javax.swing.JLabel icourse;
    private rojeru_san.componentes.RSDateChooser issuedate;
    private javax.swing.JLabel iuserid;
    private javax.swing.JLabel iusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JLabel studenterror;
    private app.bolivia.swing.JCTextField txtbookid;
    private app.bolivia.swing.JCTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}
